<body id="adminBody">
    <h1>Admin</h1>
    <ul>

        <li><a href="/employees">Show all employees</a></li>
        <li><a href="/employee-registraion">Add employee</a></li>
        
        
        TODO:
        <br>Add, Edit and Delete information for an employee
        <br>Obtain a sales report for a particular month
        <br>Produce a comprehensive listing of all flights
        <br>Produce a list of reservations by flight number or by customer name
        <br>Produce a summary listing of revenue generated by a particular flight, destination city, or customer
        <br>Determine which customer representative generated most total revenue
        <br>Determine which customer generated most total revenue
        <br>Produce a list of most active flights
        <br>Produce a list of all customers who have seats reserved on a given flight
        <br>Produce a list of all flights for a given airport
        <br>Produce a list of all flights whose arrival and departure times are on-time/delayed
    </ul>

</body>