<h2>Admin</h2>
<hr>
<div id="employeeBody">    
    
    <ul>

        <li><a href="/customer-representatives">All subordinates</a></li>
        <li><a href="/employee-registraion">Add employee</a></li>
        <li><a href="/sales">Sales report for a particular month</a></li>
        <li><a href="/flight-listing">Produce a comprehensive listing of all flights</a></li>
        TODO:
        <li><a href="/reservation-search">Produce a list of reservations by flight number or by customer name</a></li>
        <li><a href="">Produce a summary listing of revenue generated by a particular flight, destination city, or customer</a></li> 
        <!--<li><a href="">Determine which customer representative generated most total revenue</a></li>
        <li><a href="">Determine which customer generated most total revenue</a></li> -->
        <li><a href="/max-revenue">Most revenue generated</a></li>
        <li><a href="">Produce a list of most active flights</a></li>
        <li><a href="">Produce a list of all customers who have seats reserved on a given flight</a></li>
        <li><a href="/airport-search">Produce a list of all flights for a given airport</a></li>
        <li><a href="/delays">Produce a list of all flights whose arrival and departure times are on-time/delayed</a></li>
    </ul>

</div>